[tool.black]
target-version = ['py39']
extend-exclude = '''
(
  ^/arbeitszeit_flask/development_settings\.py |
  ^/arbeitszeit_flask/production_settings\.py |
  ^/migrations/
)
'''

[tool.isort]
profile = "black"
multi_line_output = 3
