# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Arbeitszeitapp CI Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      HYPOTHESIS_PROFILE: ci

    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v16
    - run: nix flake check --print-build-logs
    - run: nix build --print-build-logs
